apiVersion: v1
kind: Service
metadata:
  name: mlops-api-service-v2
spec:
  type: LoadBalancer
  selector:
    app: mlops-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      